binData.so: binData.cc /home/ponci/ROOT_CERN/build/include/TCanvas.h \
 /home/ponci/ROOT_CERN/build/include/TPad.h \
 /home/ponci/ROOT_CERN/build/include/TVirtualPad.h \
 /home/ponci/ROOT_CERN/build/include/TAttPad.h \
 /home/ponci/ROOT_CERN/build/include/Rtypes.h \
 /home/ponci/ROOT_CERN/build/include/RConfig.h \
 /home/ponci/ROOT_CERN/build/include/RVersion.h \
 /home/ponci/ROOT_CERN/build/include/DllImport.h \
 /home/ponci/ROOT_CERN/build/include/snprintf.h \
 /home/ponci/ROOT_CERN/build/include/strlcpy.h \
 /home/ponci/ROOT_CERN/build/include/TGenericClassInfo.h \
 /home/ponci/ROOT_CERN/build/include/TSchemaHelper.h \
 /home/ponci/ROOT_CERN/build/include/TVirtualX.h \
 /home/ponci/ROOT_CERN/build/include/TNamed.h \
 /home/ponci/ROOT_CERN/build/include/TObject.h \
 /home/ponci/ROOT_CERN/build/include/TStorage.h \
 /home/ponci/ROOT_CERN/build/include/TVersionCheck.h \
 /home/ponci/ROOT_CERN/build/include/TBuffer.h \
 /home/ponci/ROOT_CERN/build/include/TString.h \
 /home/ponci/ROOT_CERN/build/include/TMathBase.h \
 /home/ponci/ROOT_CERN/build/include/TAttLine.h \
 /home/ponci/ROOT_CERN/build/include/TAttFill.h \
 /home/ponci/ROOT_CERN/build/include/TAttText.h \
 /home/ponci/ROOT_CERN/build/include/TAttMarker.h \
 /home/ponci/ROOT_CERN/build/include/GuiTypes.h \
 /home/ponci/ROOT_CERN/build/include/Buttons.h \
 /home/ponci/ROOT_CERN/build/include/TQObject.h \
 /home/ponci/ROOT_CERN/build/include/TAttBBox2D.h \
 /home/ponci/ROOT_CERN/build/include/TPoint.h \
 /home/ponci/ROOT_CERN/build/include/TAttCanvas.h \
 /home/ponci/ROOT_CERN/build/include/TCanvasImp.h \
 /home/ponci/ROOT_CERN/build/include/TGraph.h \
 /home/ponci/ROOT_CERN/build/include/TVectorFfwd.h \
 /home/ponci/ROOT_CERN/build/include/TVectorDfwd.h \
 /home/ponci/ROOT_CERN/build/include/TFitResultPtr.h \
 /home/ponci/ROOT_CERN/build/include/TGraphErrors.h \
 /home/ponci/ROOT_CERN/build/include/TProfile.h \
 /home/ponci/ROOT_CERN/build/include/TH1.h \
 /home/ponci/ROOT_CERN/build/include/TAxis.h \
 /home/ponci/ROOT_CERN/build/include/TAttAxis.h \
 /home/ponci/ROOT_CERN/build/include/TArrayD.h \
 /home/ponci/ROOT_CERN/build/include/TArray.h \
 /home/ponci/ROOT_CERN/build/include/TArrayC.h \
 /home/ponci/ROOT_CERN/build/include/TArrayS.h \
 /home/ponci/ROOT_CERN/build/include/TArrayI.h \
 /home/ponci/ROOT_CERN/build/include/TArrayF.h \
 /home/ponci/ROOT_CERN/build/include/Foption.h \
 /home/ponci/ROOT_CERN/build/include/TH1.h \
 /home/ponci/ROOT_CERN/build/include/TMath.h \
 /home/ponci/ROOT_CERN/build/include/TError.h
Bindata.o: Bindata.cc Bindata.h /home/ponci/ROOT_CERN/build/include/TProfile.h \
 /home/ponci/ROOT_CERN/build/include/TH1.h \
 /home/ponci/ROOT_CERN/build/include/TAxis.h \
 /home/ponci/ROOT_CERN/build/include/TNamed.h \
 /home/ponci/ROOT_CERN/build/include/TObject.h \
 /home/ponci/ROOT_CERN/build/include/Rtypes.h \
 /home/ponci/ROOT_CERN/build/include/RConfig.h \
 /home/ponci/ROOT_CERN/build/include/RVersion.h \
 /home/ponci/ROOT_CERN/build/include/DllImport.h \
 /home/ponci/ROOT_CERN/build/include/snprintf.h \
 /home/ponci/ROOT_CERN/build/include/strlcpy.h \
 /home/ponci/ROOT_CERN/build/include/TGenericClassInfo.h \
 /home/ponci/ROOT_CERN/build/include/TSchemaHelper.h \
 /home/ponci/ROOT_CERN/build/include/TStorage.h \
 /home/ponci/ROOT_CERN/build/include/TVersionCheck.h \
 /home/ponci/ROOT_CERN/build/include/TBuffer.h \
 /home/ponci/ROOT_CERN/build/include/TString.h \
 /home/ponci/ROOT_CERN/build/include/TMathBase.h \
 /home/ponci/ROOT_CERN/build/include/TAttAxis.h \
 /home/ponci/ROOT_CERN/build/include/TArrayD.h \
 /home/ponci/ROOT_CERN/build/include/TArray.h \
 /home/ponci/ROOT_CERN/build/include/TAttLine.h \
 /home/ponci/ROOT_CERN/build/include/TAttFill.h \
 /home/ponci/ROOT_CERN/build/include/TAttMarker.h \
 /home/ponci/ROOT_CERN/build/include/TArrayC.h \
 /home/ponci/ROOT_CERN/build/include/TArrayS.h \
 /home/ponci/ROOT_CERN/build/include/TArrayI.h \
 /home/ponci/ROOT_CERN/build/include/TArrayF.h \
 /home/ponci/ROOT_CERN/build/include/Foption.h \
 /home/ponci/ROOT_CERN/build/include/TVectorFfwd.h \
 /home/ponci/ROOT_CERN/build/include/TVectorDfwd.h \
 /home/ponci/ROOT_CERN/build/include/TFitResultPtr.h \
 /home/ponci/ROOT_CERN/build/include/TH1.h
wCorrections.o: wCorrections.cc Bindata.cc Bindata.h \
 /home/ponci/ROOT_CERN/build/include/TProfile.h \
 /home/ponci/ROOT_CERN/build/include/TH1.h \
 /home/ponci/ROOT_CERN/build/include/TAxis.h \
 /home/ponci/ROOT_CERN/build/include/TNamed.h \
 /home/ponci/ROOT_CERN/build/include/TObject.h \
 /home/ponci/ROOT_CERN/build/include/Rtypes.h \
 /home/ponci/ROOT_CERN/build/include/RConfig.h \
 /home/ponci/ROOT_CERN/build/include/RVersion.h \
 /home/ponci/ROOT_CERN/build/include/DllImport.h \
 /home/ponci/ROOT_CERN/build/include/snprintf.h \
 /home/ponci/ROOT_CERN/build/include/strlcpy.h \
 /home/ponci/ROOT_CERN/build/include/TGenericClassInfo.h \
 /home/ponci/ROOT_CERN/build/include/TSchemaHelper.h \
 /home/ponci/ROOT_CERN/build/include/TStorage.h \
 /home/ponci/ROOT_CERN/build/include/TVersionCheck.h \
 /home/ponci/ROOT_CERN/build/include/TBuffer.h \
 /home/ponci/ROOT_CERN/build/include/TString.h \
 /home/ponci/ROOT_CERN/build/include/TMathBase.h \
 /home/ponci/ROOT_CERN/build/include/TAttAxis.h \
 /home/ponci/ROOT_CERN/build/include/TArrayD.h \
 /home/ponci/ROOT_CERN/build/include/TArray.h \
 /home/ponci/ROOT_CERN/build/include/TAttLine.h \
 /home/ponci/ROOT_CERN/build/include/TAttFill.h \
 /home/ponci/ROOT_CERN/build/include/TAttMarker.h \
 /home/ponci/ROOT_CERN/build/include/TArrayC.h \
 /home/ponci/ROOT_CERN/build/include/TArrayS.h \
 /home/ponci/ROOT_CERN/build/include/TArrayI.h \
 /home/ponci/ROOT_CERN/build/include/TArrayF.h \
 /home/ponci/ROOT_CERN/build/include/Foption.h \
 /home/ponci/ROOT_CERN/build/include/TVectorFfwd.h \
 /home/ponci/ROOT_CERN/build/include/TVectorDfwd.h \
 /home/ponci/ROOT_CERN/build/include/TFitResultPtr.h \
 /home/ponci/ROOT_CERN/build/include/TH1.h
weaCoefvsSec.o: weaCoefvsSec.cc /home/ponci/ROOT_CERN/build/include/TCanvas.h \
 /home/ponci/ROOT_CERN/build/include/TPad.h \
 /home/ponci/ROOT_CERN/build/include/TVirtualPad.h \
 /home/ponci/ROOT_CERN/build/include/TAttPad.h \
 /home/ponci/ROOT_CERN/build/include/Rtypes.h \
 /home/ponci/ROOT_CERN/build/include/RConfig.h \
 /home/ponci/ROOT_CERN/build/include/RVersion.h \
 /home/ponci/ROOT_CERN/build/include/DllImport.h \
 /home/ponci/ROOT_CERN/build/include/snprintf.h \
 /home/ponci/ROOT_CERN/build/include/strlcpy.h \
 /home/ponci/ROOT_CERN/build/include/TGenericClassInfo.h \
 /home/ponci/ROOT_CERN/build/include/TSchemaHelper.h \
 /home/ponci/ROOT_CERN/build/include/TVirtualX.h \
 /home/ponci/ROOT_CERN/build/include/TNamed.h \
 /home/ponci/ROOT_CERN/build/include/TObject.h \
 /home/ponci/ROOT_CERN/build/include/TStorage.h \
 /home/ponci/ROOT_CERN/build/include/TVersionCheck.h \
 /home/ponci/ROOT_CERN/build/include/TBuffer.h \
 /home/ponci/ROOT_CERN/build/include/TString.h \
 /home/ponci/ROOT_CERN/build/include/TMathBase.h \
 /home/ponci/ROOT_CERN/build/include/TAttLine.h \
 /home/ponci/ROOT_CERN/build/include/TAttFill.h \
 /home/ponci/ROOT_CERN/build/include/TAttText.h \
 /home/ponci/ROOT_CERN/build/include/TAttMarker.h \
 /home/ponci/ROOT_CERN/build/include/GuiTypes.h \
 /home/ponci/ROOT_CERN/build/include/Buttons.h \
 /home/ponci/ROOT_CERN/build/include/TQObject.h \
 /home/ponci/ROOT_CERN/build/include/TAttBBox2D.h \
 /home/ponci/ROOT_CERN/build/include/TPoint.h \
 /home/ponci/ROOT_CERN/build/include/TAttCanvas.h \
 /home/ponci/ROOT_CERN/build/include/TCanvasImp.h \
 /home/ponci/ROOT_CERN/build/include/TGraph.h \
 /home/ponci/ROOT_CERN/build/include/TVectorFfwd.h \
 /home/ponci/ROOT_CERN/build/include/TVectorDfwd.h \
 /home/ponci/ROOT_CERN/build/include/TFitResultPtr.h \
 /home/ponci/ROOT_CERN/build/include/TGraphErrors.h \
 /home/ponci/ROOT_CERN/build/include/TLatex.h \
 /home/ponci/ROOT_CERN/build/include/TText.h \
 /home/ponci/ROOT_CERN/build/include/TAxis.h \
 /home/ponci/ROOT_CERN/build/include/TAttAxis.h \
 /home/ponci/ROOT_CERN/build/include/TArrayD.h \
 /home/ponci/ROOT_CERN/build/include/TArray.h
